<a href="https://colab.research.google.com/github/Pratheekongit/DSC-Assignments/blob/master/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])
print('1-D array:')
print(a1)
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[4,5,6],[7,8,9]])
print('\n2-D array:')
print(a2)

1-D array:
[1 2 3]

2-D array:
[[4 5 6]
 [7 8 9]]


In [ ]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print("shape:",a1.shape)
print("no. of dimensions:",a1.ndim)
print("data type:",a1.dtype)
print("size:",a1.itemsize)
#print

shape: (3,)
no. of dimensions: 1
data type: int64
size: 8


In [ ]:
# Attributes of 2-dimensional array
print("shape:",a2.shape)
print("no. of dimensions:",a2.ndim)
print("data type:",a2.dtype)
print("size:",a2.itemsize)

shape: (2, 3)
no. of dimensions: 2
data type: int64
size: 8


In [ ]:
# Create an array of shape (5, 5) with only ones
np.ones([5,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# Create an array of shape (3, 3, 5) with only zeros
np.zeros([3,3,5],dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10,size=(7,2))

array([[1, 4],
       [7, 9],
       [8, 8],
       [0, 8],
       [6, 8],
       [7, 0],
       [7, 7]])

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3,5)

array([[0.01407982, 0.1988424 , 0.71134195, 0.79017554, 0.60595997],
       [0.92630088, 0.65107703, 0.91495968, 0.85003858, 0.44945067],
       [0.09541012, 0.37081825, 0.66884125, 0.66592236, 0.59129779]])

In [ ]:
# Create an array of normally distributed random numbers
x = np.random.normal(size=[4,5])
x

array([[ 0.45788508, -1.68428738,  0.32684522, -0.08111895,  0.46779475],
       [ 0.73612235, -0.77970188, -0.84389636, -0.15053386, -0.96555767],
       [ 0.15048908, -0.11342125,  2.63352822, -1.02509089, -0.78204783],
       [ 0.42394307,  0.8727051 ,  2.28722598,  1.6229205 ,  0.82373308]])

In [ ]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10,size=[4,6])

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [ ]:
# Copy the code from the cell above and run it again
arr=np.random.randint(10,size=[4,6])
arr

array([[8, 0, 9, 2, 6, 3],
       [8, 2, 4, 2, 6, 4],
       [8, 6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1, 3]])

In [ ]:
# Find the 0'th index of the latest array you created
arr[0][0]

8

In [ ]:
# Get the first 2 rows of latest array you created
arr[2:]

array([[8, 6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1, 3]])

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
arr[:2,:2]

array([[8, 0],
       [8, 2]])

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
ra1= np.random.randint(10,size=([3,5]))
ra2=np.ones([3,5],dtype=int)


In [ ]:
# Add the two arrays together
ra1+ra2

array([[7, 2, 3, 1, 5],
       [1, 8, 1, 1, 2],
       [2, 6, 7, 5, 1]])

In [ ]:
# Create another array of ones of shape (5, 3)
ro=np.ones([5,3],dtype=int)
ro

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
ra1+ra2+ro

ValueError: ignored

In [ ]:
# Do the same operation you just did but this time with a transpose on one array
rt = ro.T
rf=ra1+ra2+rt
rf

array([[8, 3, 4, 2, 6],
       [2, 9, 2, 2, 3],
       [3, 7, 8, 6, 2]])

In [ ]:
# Take the latest array to the power of 2 using the python way
rf**2

array([[64,  9, 16,  4, 36],
       [ 4, 81,  4,  4,  9],
       [ 9, 49, 64, 36,  4]])

In [ ]:
# Do the same thing with numpy way
np.square(rf)

array([[64,  9, 16,  4, 36],
       [ 4, 81,  4,  4,  9],
       [ 9, 49, 64, 36,  4]])

In [ ]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
print('mean:',np.mean(rf))
print('min:',np.min(rf))
print('max:', np.max(rf))
print('std deviation',np.std(rf))
print('variation',np.var(rf))

mean: 4.466666666666667
min: 2
max: 9
std deviation 2.4997777679003566
variation 6.248888888888888


In [ ]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
ay1=np.random.randint(10, size=(3,3))
ay2=np.random.randint(10, size=(3,2))

In [ ]:
# Perform a dot product on the two newest arrays you created
np.dot(ay1,ay2)

array([[14, 17],
       [93, 78],
       [81, 39]])

In [ ]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
y1=np.random.randint(10, size=(4,3))
y2=np.random.randint(10, size=(4,3))

In [ ]:
# Perform a hadamard product on the two newest arrays you created
np.multiply(y1,y2)


array([[32,  4, 36],
       [72, 16, 12],
       [18, 16,  9],
       [ 0,  5,  0]])

In [ ]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(y1,y2)

ValueError: ignored

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on t
y2=y2.T
np.dot(y1,y2)

array([[ 72,  84,  36, 103],
       [ 80, 100,  40, 115],
       [ 86, 142,  43, 124],
       [  4,   8,   2,   5]])

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
va1=np.random.randint(10, size=(5,5))
va2=np.random.randint(10, size=(5,5))

In [ ]:
# Compare the two arrays with '>', '<=' and '==' 
print(va1>va2)
print()
print(va1<=va2)
print()
print(va1==va2)

[[False False False False  True]
 [ True  True  True False False]
 [ True False  True False False]
 [False  True  True  True False]
 [False False False  True  True]]

[[ True  True  True  True False]
 [False False False  True  True]
 [False  True False  True  True]
 [ True False False False  True]
 [ True  True  True False False]]

[[False  True False False False]
 [False False False False False]
 [False False False False False]
 [ True False False False False]
 [False  True False False False]]


In [ ]:
# Sort one of the arrays you just created in ascending order
np.sort(va1)

array([[0, 0, 3, 7, 7],
       [2, 3, 3, 5, 7],
       [1, 1, 2, 8, 8],
       [1, 2, 3, 5, 8],
       [0, 0, 3, 3, 4]])

In [210]:
# Sort the indexes of one of the arrays you just created
np.argsort(va2)

array([[4, 3, 2, 0, 1],
       [0, 1, 2, 4, 3],
       [2, 0, 1, 3, 4],
       [2, 3, 0, 1, 4],
       [3, 4, 0, 2, 1]])

In [211]:
# Find the index with the maximum value in one of the arrays you've created
np.where(va1==np.max(va1))

(array([2, 2, 3]), array([0, 2, 3]))

In [213]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [214]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(va1,axis=1)

array([1, 2, 0, 3, 3])

In [216]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(va2,axis=0)

array([1, 1, 3, 3, 0])